export const benefitsList = [
  "ATIVAÇÃO DO METABOLISMO",
  "AUXILIA NA QUEIMA DE GORDURA",
  "REDUÇÃO DO APETITE",
  "FORMULAÇÃO LIMPA",
  "VITAMINAS PARA AUXILIAR NO PROCESSO METABÓLICO",
  "AUMENTO DE ENERGIA",
  "MELHORA A PERFORMANCE FUNCIONAL",
  "AUMENTO DA CAPACIDADE DE RESISTÊNCIA E NO DESEMPENHO DOS EXERCÍCIOS FÍSICOS",
]